import { WEBSITE_LOCALE_CODES, WEBSITE_PAGE_SLUGS } from './websiteLocales.js';

const HERO = 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=2400&q=80';
const CLASSROOM = 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?auto=format&fit=crop&w=1400&q=80';
const HERO_VIDEO = 'https://youtu.be/MAf3va2bK5w';

/** Official La Racine social channels (shared across locales) */
export const SCHOOL_SOCIALS = [
  { id: 'whatsapp', label: 'WhatsApp', url: 'https://whatsapp.com/channel/0029VbCh7bC84OmJQtxceY38' },
  { id: 'x', label: 'X', url: 'https://x.com/LaRacine64' },
  { id: 'tiktok', label: 'TikTok', url: 'https://www.tiktok.com/@ecole.la.racine' },
  { id: 'facebook', label: 'Facebook', url: 'https://www.facebook.com/share/196zUK2Wip/' },
  { id: 'instagram', label: 'Instagram', url: 'https://www.instagram.com/ecolelaracine_gisenyi' },
  { id: 'youtube', label: 'YouTube', url: 'https://youtu.be/MAf3va2bK5w' },
];

const PAGE_LABELS = {
  nav: 'Navigation & footer',
  home: 'Home',
  about: 'About',
  academics: 'Academics',
  locations: 'Campuses',
  announcements: 'Announcements',
  news: 'News',
  events: 'Events',
  gallery: 'Gallery',
  admissions: 'Admissions',
  contact: 'Contact',
};

const defaults = {
  en: {
    nav: {
      brandTag: 'School',
      menuSchool: 'School',
      menuLife: 'School life',
      about: 'About',
      academics: 'Academics',
      locations: 'Campuses',
      announcements: 'Announcements',
      admissions: 'Admissions',
      contact: 'Contact',
      portal: 'Portal',
      apply: 'Apply',
      mobilePortal: 'Staff & family portal',
      footerExplore: 'Explore',
      footerContact: 'Contact',
      footerPortal: 'Open school portal',
      footerFollow: 'Follow us',
      copyrightSuffix: 'All rights reserved.',
      socials: SCHOOL_SOCIALS,
    },
    home: {
      heroImageUrl: HERO,
      heroVideoUrl: HERO_VIDEO,
      heroEyebrow: 'Bilingual school · Rubavu & Gisenyi',
      heroTitle: 'Shaping bright futures through quality education',
      heroLine: 'A calm, rigorous bilingual education where discipline, intelligence, and innovation shape every learner.',
      heroCtaPrimary: 'Apply now',
      heroCtaSecondary: 'Why La Racine',
      heroSlides: [
        {
          eyebrow: 'Bilingual school · Rubavu',
          title: 'Shaping bright futures through quality education',
          body: 'A world-class bilingual education in English and French — from early years through primary.',
          ctaPrimary: 'Apply now',
          ctaPrimaryTo: '/admissions/apply',
          ctaSecondary: 'Why La Racine',
          ctaSecondaryTo: '/about',
          imageUrl: HERO,
        },
        {
          eyebrow: 'Rubavu & Gisenyi',
          title: 'Nurturing excellence across our campuses',
          body: 'Modern classrooms and dedicated teachers helping every student reach their full potential.',
          ctaPrimary: 'Our campuses',
          ctaPrimaryTo: '/locations',
          ctaSecondary: 'Contact us',
          ctaSecondaryTo: '/contact',
          imageUrl: CLASSROOM,
        },
        {
          eyebrow: 'Nursery to primary',
          title: 'Learning that is clear, calm, and ambitious',
          body: 'Structured programs that prepare children for the next stage of life — with families as partners.',
          ctaPrimary: 'Our programs',
          ctaPrimaryTo: '/academics',
          ctaSecondary: 'Student life',
          ctaSecondaryTo: '/gallery',
          imageUrl: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=2400&q=80',
        },
      ],
      stats: { campuses: 2, students: '400+', languages: '2', focus: '100%' },
      statCampusesLabel: 'Campuses in Rubavu',
      statStudentsLabel: 'Students growing with us',
      statLanguagesLabel: 'Languages of instruction',
      statFocusLabel: 'Commitment to every child',
      programsLabel: 'Our educational programs',
      programsTitle: 'Excellence at every stage',
      programsLead: 'From early childhood to primary, programs designed to unlock every student’s potential.',
      programsExplore: 'Explore program',
      programs: [
        {
          tag: 'Early years',
          title: 'Nursery',
          body: 'A safe, stimulating environment where young minds begin through play-based learning and bilingual immersion.',
          points: ['Play-based learning', 'Bilingual immersion from day one'],
          imageUrl: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=1200&q=80',
          to: '/academics',
          cta: 'Explore Nursery',
        },
        {
          tag: 'Foundation years',
          title: 'Primary',
          body: 'Strong foundations in literacy, numeracy, and critical thinking — with clear assessment and bulletin reporting.',
          points: ['Core academics & languages', 'Critical thinking & creativity'],
          imageUrl: CLASSROOM,
          to: '/academics',
          cta: 'Explore Primary',
        },
        {
          tag: 'Growing minds',
          title: 'Beyond the desk',
          body: 'Homework, library, and activities that stretch talent outside the timetable — so children grow as whole people.',
          points: ['Homework & e-learning', 'Clubs and school life'],
          imageUrl: HERO,
          to: '/academics',
          cta: 'Explore learning life',
        },
      ],
      newsLabel: 'Latest updates',
      newsTitle: "What's happening at our school",
      newsLead: 'Stay informed with the latest news, events, and achievements from our campuses.',
      newsAll: 'View all news',
      whoLabel: 'Who we are',
      whoTitle: 'Rooted in Rubavu. Growing confident minds.',
      whoLead: 'École La RACINE serves families across Gisenyi and Rubavu with a calm, rigorous learning culture — from early years through primary.',
      whoCtaStory: 'Our story',
      whoCtaAcademics: 'Academic life',
      whoImageUrl: CLASSROOM,
      whoImageAlt: 'Students learning together in a bright classroom',
      whyLabel: 'Our commitment',
      whyTitle: 'Why families choose La Racine',
      whyLead: 'Education that nurtures academic excellence and character — preparing students for a confident future.',
      whyCaption: 'Among Rubavu’s trusted bilingual schools',
      whyChoose: [
        { title: 'Guiding hearts', body: 'Pastoral care and clear values help children feel safe, respected, and ready to learn.' },
        { title: 'Shaping minds', body: 'Ambitious teaching, bilingual confidence, and transparent progress for every learner.' },
        { title: 'Bilingual excellence', body: 'French and English woven through the school day — opening doors at home and beyond.' },
        { title: 'Discipline & well-being', body: 'We never compromise on structure, kindness, and a calm learning environment.' },
        { title: 'Healthy routines', body: 'School life that supports concentration, friendship, and healthy habits.' },
        { title: 'Exceptional care', body: 'We treat parents as partners — with clear communication through the family portal.' },
      ],
      promiseLabel: 'Our promise',
      promiseTitle: 'Discipline · Intelligence · Innovation',
      promiseLead: 'Three values guide teaching, pastoral care, and every partnership with parents — so children leave ready for the next stage of life.',
      values: [
        { title: 'Discipline', body: 'Clear routines, respectful community, and habits that free children to focus on learning.' },
        { title: 'Intelligence', body: 'Curiosity, reading, reasoning, and bilingual confidence across the school day.' },
        { title: 'Innovation', body: 'Modern tools, creative projects, and teachers who keep improving how children learn.' },
      ],
      galleryLabel: 'Capturing moments',
      galleryTitle: 'School life gallery',
      galleryLead: 'The vibrant life at La Racine — learning, activities, and memorable campus moments.',
      galleryAll: 'Open full gallery',
      voicesLabel: 'What they say',
      voicesTitle: 'Voices of our community',
      voicesLead: 'Hear from parents and students about their experience at La Racine.',
      testimonials: [
        {
          quote: 'La Racine gives our child clear routines and warm teachers. We always know how learning is going through the portal.',
          name: 'Parent family',
          role: 'Primary · Rubavu',
        },
        {
          quote: 'The bilingual classroom helped our daughter speak with confidence in both French and English.',
          name: 'Parent family',
          role: 'Nursery · Gisenyi',
        },
        {
          quote: 'Discipline here is kind but firm. Children feel safe, and teachers take every learner seriously.',
          name: 'Parent family',
          role: 'School community',
        },
      ],
      nextLabel: 'Begin your child’s journey',
      nextTitle: 'Ready to join La Racine?',
      nextLead: 'Admissions are open across our Rubavu campuses. Apply online in minutes, or contact the school to visit.',
      nextCtaAdmissions: 'Apply now',
      nextCtaContact: 'Book a visit',
      nextCtaPortal: 'Family portal',
      enrollTitle: 'Admissions are open',
      enrollBody: 'Applications for the new academic year are being accepted.',
      enrollCta: 'Apply now',
    },
    about: {
      label: 'About',
      title: 'A school with roots — and room to grow',
      lead: 'École La RACINE is a community school in Rwanda’s Western Province, built around the belief that strong character and sharp minds belong together.',
      missionLabel: 'Mission',
      missionTitle: 'Educate the whole child',
      missionLead: 'We form learners who are grounded, curious, and ready to contribute — at home, in class, and in the wider Rubavu community.',
      whereTitle: 'Where we stand',
      valuesTitle: 'What we live by',
      familiesTitle: 'How families connect',
      familiesBody: 'Parents follow learning, attendance, fees, and messages through the La Racine portal — so school and home stay in sync.',
      ctaCampuses: 'See campuses',
      ctaAdmissions: 'Admissions',
    },
    academics: {
      label: 'Academics',
      title: 'Learning that is clear, calm, and ambitious',
      lead: 'Teachers follow a structured curriculum with transparent marks and bulletin reporting — so families always know how a child is progressing.',
      programs: [
        { title: 'Nursery & early years', body: 'Warm classrooms, play with purpose, and first steps in language, number sense, and social confidence.' },
        { title: 'Primary pathway', body: 'A clear academic arc across core domains — literacy, mathematics, science, and civic formation — with regular assessment.' },
        { title: 'Learning beyond the desk', body: 'Homework, e-learning, library time, and activities that stretch talent outside the timetable.' },
      ],
      ctaPlacement: 'Ask about placement',
      ctaPortal: 'View learning portal',
    },
    locations: {
      label: 'Campuses',
      title: 'Two campuses. One La Racine standard.',
      lead: 'Choose the campus closest to your family — both share the same values, academic expectations, and care for every learner.',
      empty: 'Campus details will appear here soon. Contact the school office for directions.',
      ctaVisit: 'Book a visit',
      ctaAdmissions: 'Admissions',
      mapTitle: 'Find us on the map',
      mapLead: 'Open our school location in Google Maps for directions.',
      mapCta: 'Open in Google Maps',
      mapUrl: 'https://maps.app.goo.gl/GGVeh9pcUptx14oG6',
      mapEmbedUrl: 'https://maps.google.com/maps?q=-1.6948639,29.2523412&z=17&output=embed',
    },
    admissions: {
      label: 'Admissions',
      title: 'Join a school that takes your child’s growth seriously',
      lead: 'Admissions at La Racine are personal and clear. We help families find the right class and settle into school life with confidence.',
      steps: [
        { title: 'Discover the school', body: 'Read about our campuses and academics, then choose the campus that fits your family.' },
        { title: 'Apply online', body: 'Submit the admission form online — no account required. Attach the birth certificate and a photo.' },
        { title: 'School review & portal access', body: 'After approval, the school creates family accounts so you can follow attendance, bulletin, homework, and fees.' },
      ],
      ctaApply: 'Apply online',
      ctaContact: 'Contact admissions',
      ctaPortal: 'Open parent portal',
    },
    contact: {
      label: 'Contact',
      title: 'We are ready to welcome your family',
      lead: 'Reach the school office by phone or email. For day-to-day school life after enrolment, use the secure family portal.',
      officeTitle: 'School office',
      campusesTitle: 'Campus lines',
      ctaPortal: 'Family & staff portal',
      mapTitle: 'Our location',
      mapLead: 'Find École La Racine on Google Maps.',
      mapCta: 'Open in Google Maps',
      mapUrl: 'https://maps.app.goo.gl/GGVeh9pcUptx14oG6',
      mapEmbedUrl: 'https://maps.google.com/maps?q=-1.6948639,29.2523412&z=17&output=embed',
    },
  },

  fr: {
    nav: {
      brandTag: 'École',
      menuSchool: 'École',
      menuLife: 'Vie scolaire',
      about: 'À propos',
      academics: 'Scolarité',
      locations: 'Campus',
      announcements: 'Annonces',
      admissions: 'Admissions',
      contact: 'Contact',
      portal: 'Portail',
      apply: 'Postuler',
      mobilePortal: 'Portail personnel & familles',
      footerExplore: 'Explorer',
      footerContact: 'Contact',
      footerPortal: 'Ouvrir le portail scolaire',
      footerFollow: 'Suivez-nous',
      copyrightSuffix: 'Tous droits réservés.',
      socials: SCHOOL_SOCIALS,
    },
    home: {
      heroImageUrl: HERO,
      heroVideoUrl: HERO_VIDEO,
      heroEyebrow: 'École bilingue · Rubavu & Gisenyi',
      heroTitle: 'Former des avenirs brillants par une éducation de qualité',
      heroLine: 'Une éducation bilingue calme et exigeante où la discipline, l’intelligence et l’innovation forment chaque élève.',
      heroCtaPrimary: 'Postuler',
      heroCtaSecondary: 'Pourquoi La Racine',
      heroSlides: [
        {
          eyebrow: 'École bilingue · Rubavu',
          title: 'Former des avenirs brillants par une éducation de qualité',
          body: 'Une éducation bilingue en français et en anglais — de la maternelle au primaire.',
          ctaPrimary: 'Postuler',
          ctaPrimaryTo: '/admissions/apply',
          ctaSecondary: 'Pourquoi La Racine',
          ctaSecondaryTo: '/about',
          imageUrl: HERO,
        },
        {
          eyebrow: 'Rubavu & Gisenyi',
          title: 'L’excellence sur nos campus',
          body: 'Des classes modernes et des enseignants dédiés pour que chaque élève atteigne son potentiel.',
          ctaPrimary: 'Nos campus',
          ctaPrimaryTo: '/locations',
          ctaSecondary: 'Nous contacter',
          ctaSecondaryTo: '/contact',
          imageUrl: CLASSROOM,
        },
      ],
      stats: { campuses: 2, students: '400+', languages: '2', focus: '100%' },
      statCampusesLabel: 'Campus à Rubavu',
      statStudentsLabel: 'Élèves qui grandissent avec nous',
      statLanguagesLabel: 'Langues d’enseignement',
      statFocusLabel: 'Engagement pour chaque enfant',
      programsLabel: 'Nos programmes',
      programsTitle: 'L’excellence à chaque étape',
      programsLead: 'De la petite enfance au primaire, des programmes conçus pour révéler le potentiel de chaque élève.',
      programsExplore: 'Découvrir le programme',
      programs: [
        {
          tag: 'Petite enfance',
          title: 'Maternelle',
          body: 'Un environnement sûr et stimulant où les jeunes esprits commencent par le jeu et l’immersion bilingue.',
          points: ['Apprentissage par le jeu', 'Immersion bilingue dès le premier jour'],
          imageUrl: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=1200&q=80',
          to: '/academics',
          cta: 'Découvrir la maternelle',
        },
        {
          tag: 'Fondations',
          title: 'Primaire',
          body: 'Des bases solides en lecture, calcul et pensée critique — avec un suivi clair et des bulletins.',
          points: ['Savoirs fondamentaux & langues', 'Créativité et raisonnement'],
          imageUrl: CLASSROOM,
          to: '/academics',
          cta: 'Découvrir le primaire',
        },
        {
          tag: 'Esprit en croissance',
          title: 'Au-delà de la classe',
          body: 'Devoirs, bibliothèque et activités qui étendent les talents hors de l’emploi du temps.',
          points: ['Devoirs & e-learning', 'Clubs et vie scolaire'],
          imageUrl: HERO,
          to: '/academics',
          cta: 'Découvrir la vie scolaire',
        },
      ],
      newsLabel: 'Actualités',
      newsTitle: 'Ce qui se passe à l’école',
      newsLead: 'Restez informés des dernières nouvelles, événements et réussites de nos campus.',
      newsAll: 'Toutes les actualités',
      whoLabel: 'Qui nous sommes',
      whoTitle: 'Enracinés à Rubavu. Des esprits confiants.',
      whoLead: 'École La RACINE accompagne les familles de Gisenyi et Rubavu avec une culture d’apprentissage calme et exigeante — de la maternelle au primaire.',
      whoCtaStory: 'Notre histoire',
      whoCtaAcademics: 'Vie scolaire',
      whoImageUrl: CLASSROOM,
      whoImageAlt: 'Élèves apprenant ensemble dans une classe lumineuse',
      whyLabel: 'Notre engagement',
      whyTitle: 'Pourquoi les familles choisissent La Racine',
      whyLead: 'Une éducation qui nourrit l’excellence académique et le caractère — pour un avenir confiant.',
      whyCaption: 'Une école bilingue de confiance à Rubavu',
      whyChoose: [
        { title: 'Guider les cœurs', body: 'Un accompagnement pastoral et des valeurs claires pour que chaque enfant se sente en sécurité.' },
        { title: 'Former les esprits', body: 'Un enseignement ambitieux, une confiance bilingue et une progression transparente.' },
        { title: 'Excellence bilingue', body: 'Le français et l’anglais tissent la journée scolaire — ouvrant des portes ici et ailleurs.' },
        { title: 'Discipline & bien-être', body: 'Nous ne transigeons pas sur la structure, la bienveillance et un climat calme.' },
        { title: 'Routines saines', body: 'Une vie scolaire qui soutient la concentration, l’amitié et de bonnes habitudes.' },
        { title: 'Soin exceptionnel', body: 'Les parents sont des partenaires — avec une communication claire via le portail famille.' },
      ],
      promiseLabel: 'Notre engagement',
      promiseTitle: 'Discipline · Intelligence · Innovation',
      promiseLead: 'Trois valeurs guident l’enseignement, l’accompagnement et le partenariat avec les parents — pour que chaque enfant soit prêt pour la suite.',
      values: [
        { title: 'Discipline', body: 'Des routines claires, une communauté respectueuse et des habitudes qui aident l’enfant à apprendre.' },
        { title: 'Intelligence', body: 'Curiosité, lecture, raisonnement et confiance bilingue tout au long de la journée.' },
        { title: 'Innovation', body: 'Outils modernes, projets créatifs et enseignants qui améliorent sans cesse les apprentissages.' },
      ],
      galleryLabel: 'Instants capturés',
      galleryTitle: 'Galerie de la vie scolaire',
      galleryLead: 'La vie vibrante à La Racine — apprentissages, activités et moments mémorables.',
      galleryAll: 'Ouvrir la galerie',
      voicesLabel: 'Ils en parlent',
      voicesTitle: 'Voix de notre communauté',
      voicesLead: 'Écoutez parents et élèves parler de leur expérience à La Racine.',
      testimonials: [
        {
          quote: 'La Racine offre à notre enfant des routines claires et des enseignants bienveillants. Le portail nous tient informés.',
          name: 'Famille parent',
          role: 'Primaire · Rubavu',
        },
        {
          quote: 'La classe bilingue a aidé notre fille à parler avec confiance en français et en anglais.',
          name: 'Famille parent',
          role: 'Maternelle · Gisenyi',
        },
        {
          quote: 'La discipline est ferme et bienveillante. Les enfants se sentent en sécurité.',
          name: 'Famille parent',
          role: 'Communauté scolaire',
        },
      ],
      nextLabel: 'Commencez le parcours de votre enfant',
      nextTitle: 'Prêt à rejoindre La Racine ?',
      nextLead: 'Les admissions sont ouvertes sur nos campus de Rubavu. Postulez en ligne en quelques minutes, ou contactez l’école pour une visite.',
      nextCtaAdmissions: 'Postuler',
      nextCtaContact: 'Réserver une visite',
      nextCtaPortal: 'Portail famille',
      enrollTitle: 'Admissions ouvertes',
      enrollBody: 'Les candidatures pour la nouvelle année scolaire sont acceptées.',
      enrollCta: 'Postuler',
    },
    about: {
      label: 'À propos',
      title: 'Une école avec des racines — et de l’espace pour grandir',
      lead: 'École La RACINE est une école communautaire de la Province de l’Ouest au Rwanda, fondée sur l’idée que le caractère et l’esprit vont ensemble.',
      missionLabel: 'Mission',
      missionTitle: 'Former l’enfant dans sa totalité',
      missionLead: 'Nous formons des apprenants ancrés, curieux et prêts à contribuer — à la maison, en classe et dans la communauté de Rubavu.',
      whereTitle: 'Où nous sommes',
      valuesTitle: 'Ce que nous vivons',
      familiesTitle: 'Comment les familles se connectent',
      familiesBody: 'Les parents suivent l’apprentissage, la présence, les frais et les messages via le portail La Racine — pour que l’école et la maison restent alignées.',
      ctaCampuses: 'Voir les campus',
      ctaAdmissions: 'Admissions',
    },
    academics: {
      label: 'Scolarité',
      title: 'Un apprentissage clair, calme et ambitieux',
      lead: 'Les enseignants suivent un programme structuré avec des notes transparentes et des bulletins — pour que les familles suivent la progression.',
      programs: [
        { title: 'Maternelle & petite enfance', body: 'Classes accueillantes, jeu utile, et premiers pas en langue, nombres et confiance sociale.' },
        { title: 'Parcours primaire', body: 'Un parcours clair en littératie, mathématiques, sciences et formation civique — avec évaluation régulière.' },
        { title: 'Au-delà du pupitre', body: 'Devoirs, e-learning, bibliothèque et activités qui développent les talents hors emploi du temps.' },
      ],
      ctaPlacement: 'Demander une place',
      ctaPortal: 'Voir le portail d’apprentissage',
    },
    locations: {
      label: 'Campus',
      title: 'Deux campus. Un même standard La Racine.',
      lead: 'Choisissez le campus le plus proche — les deux partagent les mêmes valeurs, exigences et attention pour chaque élève.',
      empty: 'Les détails des campus apparaîtront bientôt. Contactez le secrétariat pour les indications.',
      ctaVisit: 'Réserver une visite',
      ctaAdmissions: 'Admissions',
      mapTitle: 'Nous trouver sur la carte',
      mapLead: 'Ouvrez notre emplacement dans Google Maps pour l’itinéraire.',
      mapCta: 'Ouvrir dans Google Maps',
      mapUrl: 'https://maps.app.goo.gl/GGVeh9pcUptx14oG6',
      mapEmbedUrl: 'https://maps.google.com/maps?q=-1.6948639,29.2523412&z=17&output=embed',
    },
    admissions: {
      label: 'Admissions',
      title: 'Rejoignez une école qui prend au sérieux la croissance de votre enfant',
      lead: 'Les admissions à La Racine sont personnelles et claires. Nous aidons les familles à trouver la bonne classe et à s’installer sereinement.',
      steps: [
        { title: 'Découvrir l’école', body: 'Lisez nos pages campus et scolarité, puis choisissez le campus qui convient à votre famille.' },
        { title: 'Postuler en ligne', body: 'Déposez le dossier d’admission en ligne — sans compte. Joignez l’acte de naissance et une photo.' },
        { title: 'Validation & accès portail', body: 'Après validation, l’école crée les comptes famille pour suivre présence, bulletin, devoirs et frais.' },
      ],
      ctaApply: 'Postuler en ligne',
      ctaContact: 'Contacter les admissions',
      ctaPortal: 'Ouvrir le portail parent',
    },
    contact: {
      label: 'Contact',
      title: 'Nous sommes prêts à accueillir votre famille',
      lead: 'Contactez le secrétariat par téléphone ou e-mail. Après l’inscription, utilisez le portail sécurisé pour la vie scolaire quotidienne.',
      officeTitle: 'Secrétariat',
      campusesTitle: 'Lignes des campus',
      ctaPortal: 'Portail familles & personnel',
      mapTitle: 'Notre emplacement',
      mapLead: 'Trouvez École La Racine sur Google Maps.',
      mapCta: 'Ouvrir dans Google Maps',
      mapUrl: 'https://maps.app.goo.gl/GGVeh9pcUptx14oG6',
      mapEmbedUrl: 'https://maps.google.com/maps?q=-1.6948639,29.2523412&z=17&output=embed',
    },
  },

  sw: {
    nav: {
      brandTag: 'Shule',
      menuSchool: 'Shule',
      menuLife: 'Maisha ya shule',
      about: 'Kuhusu',
      academics: 'Masomo',
      locations: 'Kampasi',
      announcements: 'Matangazo',
      admissions: 'Uandikishaji',
      contact: 'Mawasiliano',
      portal: 'Portal',
      apply: 'Omba',
      mobilePortal: 'Portal ya wafanyakazi na familia',
      footerExplore: 'Chunguza',
      footerContact: 'Mawasiliano',
      footerPortal: 'Fungua portal ya shule',
      footerFollow: 'Tufuate',
      copyrightSuffix: 'Haki zote zimehifadhiwa.',
      socials: SCHOOL_SOCIALS,
    },
    home: {
      heroImageUrl: HERO,
      heroVideoUrl: HERO_VIDEO,
      heroLine: 'Shule ya lugha mbili huko Rubavu ambapo nidhamu, akili na ubunifu huunda kila mwanafunzi.',
      heroCtaPrimary: 'Anza uandikishaji',
      heroCtaSecondary: 'Tembelea kampasi zetu',
      whoLabel: 'Sisi ni nani',
      whoTitle: 'Tumejikita Rubavu. Tunakuza akili zenye ujasiri.',
      whoLead: 'École La RACINE inahudumia familia za Gisenyi na Rubavu kwa utamaduni wa kujifunza wenye utulivu na nidhamu — kutoka awamu ya awali hadi msingi.',
      whoCtaStory: 'Hadithi yetu',
      whoCtaAcademics: 'Maisha ya masomo',
      whoImageUrl: CLASSROOM,
      whoImageAlt: 'Wanafunzi wakijifunza pamoja darasani',
      promiseLabel: 'Ahadi yetu',
      promiseTitle: 'Nidhamu · Akili · Ubunifu',
      promiseLead: 'Thamani tatu huongoza ufundishaji, malezi na ushirikiano na wazazi — ili watoto wawe tayari kwa hatua inayofuata.',
      values: [
        { title: 'Nidhamu', body: 'Taratibu wazi, jamii yenye heshima, na tabia zinazosaidia watoto kuzingatia kujifunza.' },
        { title: 'Akili', body: 'Udadisi, kusoma, kufikiri, na ujasiri wa lugha mbili siku nzima.' },
        { title: 'Ubunifu', body: 'Zana za kisasa, miradi ya ubunifu, na walimu wanaoboresha jinsi watoto wanavyojifunza.' },
      ],
      nextLabel: 'Hatua inayofuata',
      nextTitle: 'Uko tayari kujiunga na La Racine?',
      nextLead: 'Tembelea kampasi, zungumza na uandikishaji, au fungua portal ya familia kuanza usajili.',
      nextCtaAdmissions: 'Mwongozo wa uandikishaji',
      nextCtaContact: 'Tuzungumze',
      nextCtaPortal: 'Portal ya familia',
    },
    about: {
      label: 'Kuhusu',
      title: 'Shule yenye mizizi — na nafasi ya kukua',
      lead: 'École La RACINE ni shule ya jamii katika Mkoa wa Magharibi wa Rwanda, iliyojengwa juu ya imani kwamba tabia njema na akili kali huenda pamoja.',
      missionLabel: 'Dhamira',
      missionTitle: 'Kuelimisha mtoto mzima',
      missionLead: 'Tunaunda wanafunzi wenye mizizi, udadisi, na utayari kuchangia — nyumbani, darasani, na katika jamii ya Rubavu.',
      whereTitle: 'Tulipo',
      valuesTitle: 'Tunachoishi',
      familiesTitle: 'Jinsi familia zinavyounganishwa',
      familiesBody: 'Wazazi hufuatilia masomo, mahudhurio, ada na ujumbe kupitia portal ya La Racine — shule na nyumbani zibaki pamoja.',
      ctaCampuses: 'Angalia kampasi',
      ctaAdmissions: 'Uandikishaji',
    },
    academics: {
      label: 'Masomo',
      title: 'Kujifunza kwa uwazi, utulivu na lengo',
      lead: 'Walimu hufuata mtaala uliopangwa na alama wazi na ripoti — familia daima zijue maendeleo ya mtoto.',
      programs: [
        { title: 'Chekechea na miaka ya awali', body: 'Madarasa ya joto, michezo yenye lengo, na hatua za kwanza za lugha, nambari na ujasiri wa kijamii.' },
        { title: 'Njia ya msingi', body: 'Mstari wa masomo katika kusoma, hisabati, sayansi na malezi ya uraia — na tathmini ya kawaida.' },
        { title: 'Zaidi ya dawati', body: 'Kazi za nyumbani, e-learning, maktaba na shughuli zinazopanua vipaji nje ya ratiba.' },
      ],
      ctaPlacement: 'Uliza kuhusu nafasi',
      ctaPortal: 'Angalia portal ya kujifunza',
    },
    locations: {
      label: 'Kampasi',
      title: 'Kampasi mbili. Kiwango kimoja cha La Racine.',
      lead: 'Chagua kampasi iliyo karibu na familia yako — zote mbili zinashiriki maadili, matarajio ya masomo na huduma kwa kila mwanafunzi.',
      empty: 'Maelezo ya kampasi yataonekana hivi karibuni. Wasiliana na ofisi kwa maelekezo.',
      ctaVisit: 'Panga ziara',
      ctaAdmissions: 'Uandikishaji',
      mapTitle: 'Tupate kwenye ramani',
      mapLead: 'Fungua eneo letu katika Google Maps kwa maelekezo.',
      mapCta: 'Fungua katika Google Maps',
      mapUrl: 'https://maps.app.goo.gl/GGVeh9pcUptx14oG6',
      mapEmbedUrl: 'https://maps.google.com/maps?q=-1.6948639,29.2523412&z=17&output=embed',
    },
    admissions: {
      label: 'Uandikishaji',
      title: 'Jiunge na shule inayochukua ukuaji wa mtoto wako kwa uzito',
      lead: 'Uandikishaji katika La Racine ni wa kibinafsi na wazi. Tunasaidia familia kupata darasa sahihi na kuingia maishani mwa shule kwa ujasiri.',
      steps: [
        { title: 'Gundua shule', body: 'Soma kuhusu kampasi na masomo, kisha chagua kampasi inayofaa familia yako.' },
        { title: 'Omba mtandaoni', body: 'Wasilisha fomu ya uandikishaji mtandaoni — bila akaunti. Ambatanisha cheti cha kuzaliwa na picha.' },
        { title: 'Ukaguzi & portal', body: 'Baada ya kuidhinishwa, shule huunda akaunti za familia ili kufuatilia mahudhurio, ripoti, kazi na ada.' },
      ],
      ctaApply: 'Omba mtandaoni',
      ctaContact: 'Wasiliana na uandikishaji',
      ctaPortal: 'Fungua portal ya mzazi',
    },
    contact: {
      label: 'Mawasiliano',
      title: 'Tuko tayari kukaribisha familia yako',
      lead: 'Wasiliana na ofisi ya shule kwa simu au barua pepe. Baada ya kujiandikisha, tumia portal salama kwa maisha ya kila siku shuleni.',
      officeTitle: 'Ofisi ya shule',
      campusesTitle: 'Simu za kampasi',
      ctaPortal: 'Portal ya familia na wafanyakazi',
      mapTitle: 'Eneo letu',
      mapLead: 'Pata École La Racine kwenye Google Maps.',
      mapCta: 'Fungua katika Google Maps',
      mapUrl: 'https://maps.app.goo.gl/GGVeh9pcUptx14oG6',
      mapEmbedUrl: 'https://maps.google.com/maps?q=-1.6948639,29.2523412&z=17&output=embed',
    },
  },

  rw: {
    nav: {
      brandTag: 'Ishuri',
      menuSchool: 'Ishuri',
      menuLife: 'Ubuzima bw’ishuri',
      about: 'Abo turi',
      academics: 'Amasomo',
      locations: 'Kampasi',
      announcements: 'Amatangazo',
      admissions: 'Kwiyandikisha',
      contact: 'Twandikire',
      portal: 'Portal',
      apply: 'Saba',
      mobilePortal: 'Portal y’abakozi n’imiryango',
      footerExplore: 'Shakisha',
      footerContact: 'Twandikire',
      footerPortal: 'Fungura portal y’ishuri',
      footerFollow: 'Dukurikire',
      copyrightSuffix: 'Uburenganzira bwose burarinzwe.',
      socials: SCHOOL_SOCIALS,
    },
    home: {
      heroImageUrl: HERO,
      heroVideoUrl: HERO_VIDEO,
      heroLine: 'Ishuri ry’indimi ebyiri i Rubavu aho inyigisho, ubwenge n’ubuhanga biforma umunyeshuri wese.',
      heroCtaPrimary: 'Tangira kwiyandikisha',
      heroCtaSecondary: 'Sura kampasi zacu',
      whoLabel: 'Abo turi',
      whoTitle: 'Turashinze imizi i Rubavu. Turakura ubwenge bufite icyizere.',
      whoLead: 'École La RACINE ikorera imiryango yo i Gisenyi no i Rubavu mu buryo bw’imyigire ifite ubwitonzi n’uburakeye — kuva mu mategeko y’uburere kugeza ku ishuri ribanza.',
      whoCtaStory: 'Amateka yacu',
      whoCtaAcademics: 'Ubuzima bw’amasomo',
      whoImageUrl: CLASSROOM,
      whoImageAlt: 'Abanyeshuri biga hamwe mu ishuri ry’umucyo',
      promiseLabel: 'Isezerano ryacu',
      promiseTitle: 'Inyigisho · Ubwenge · Ubuhanga',
      promiseLead: 'Indangagaciro eshatu ziyobora uburezi, ubwitabire n’ubufatanye n’ababyeyi — kugira ngo abana basohoke biteguye icyiciro gikurikira.',
      values: [
        { title: 'Inyigisho', body: 'Imigenzo isobanutse, umuryango wubaha abandi, n’imico ifasha abana kwibanda ku kwiga.' },
        { title: 'Ubwenge', body: 'Amatsiko, gusoma, gutekereza, n’icyizere cy’indimi ebyiri mu gihe cyose cy’ishuri.' },
        { title: 'Ubuhanga', body: 'Ibikoresho bigezweho, imishinga y’ubuhanga, n’abarimu bakomeza kunoza uko abana biga.' },
      ],
      nextLabel: 'Intambwe ikurikira',
      nextTitle: 'Witeguye kwinjira muri La Racine?',
      nextLead: 'Sura kampasi, vugana n’abashinzwe kwakira abanyeshuri, cyangwa fungura portal y’umuryango utangire kwiyandikisha.',
      nextCtaAdmissions: 'Ubuyobozi bwo kwiyandikisha',
      nextCtaContact: 'Tuvugishe',
      nextCtaPortal: 'Portal y’umuryango',
    },
    about: {
      label: 'Abo turi',
      title: 'Ishuri rifite imizi — n’umwanya wo gukura',
      lead: 'École La RACINE ni ishuri ry’umuryango mu Ntara y’Iburengerazuba y’u Rwanda, rishingiye ku gitekerezo ko imico myiza n’ubwenge bukomeye bigomba kujya hamwe.',
      missionLabel: 'Intego',
      missionTitle: 'Kubaka umwana wuzuye',
      missionLead: 'Tubaka abanyeshuri bashingiye ku mizi, bafite amatsiko, kandi biteguye gutanga umusanzu — mu rugo, mu ishuri, no mu muryango wa Rubavu.',
      whereTitle: 'Aho turi',
      valuesTitle: 'Icyo tubaho',
      familiesTitle: 'Uko imiryango ihura n’ishuri',
      familiesBody: 'Ababyeyi bakurikirana amasomo, kubahiriza, amafaranga n’ubutumwa binyuze muri portal ya La Racine — ishuri n’urugo bigume bihuje.',
      ctaCampuses: 'Reba kampasi',
      ctaAdmissions: 'Kwiyandikisha',
    },
    academics: {
      label: 'Amasomo',
      title: 'Kwiga bisobanutse, bitonze kandi bifite intego',
      lead: 'Abarimu bakurikiza porogaramu ifite imiterere isobanutse n’amanota n’ibiro — imiryango ikamenya uko umwana atera imbere.',
      programs: [
        { title: 'Y’abato n’imyaka y’uburere', body: 'Amasomo ashyushye, imikino ifite intego, n’intambwe za mbere mu ndimi, imibare n’icyizere mu muryango.' },
        { title: 'Inzira y’ishuri ribanza', body: 'Urutonde rw’amasomo mu gusoma, imibare, ubumenyi n’uburere bw’ubwenegihugu — hamwe n’ipimwa rihoraho.' },
        { title: 'Birenze ikibaho', body: 'Imikoro, e-learning, isomero n’ibikorwa byagura ubushobozi hanze y’igenekerezo.' },
      ],
      ctaPlacement: 'Baza ku mwanya',
      ctaPortal: 'Reba portal yo kwiga',
    },
    locations: {
      label: 'Kampasi',
      title: 'Kampasi ebyiri. Uburyo bumwe bwa La Racine.',
      lead: 'Hitamo kampasi iri hafi y’umuryango wawe — zombi zifite indangagaciro zimwe, ibyifuzo by’amasomo n’ubwitabire kuri umunyeshuri wese.',
      empty: 'Ibisobanuro bya kampasi bizagaragara vuba. Twandikire ku biro kugira ngo ubone inzira.',
      ctaVisit: 'Teganya gusura',
      ctaAdmissions: 'Kwiyandikisha',
      mapTitle: 'Dushake ku ikarita',
      mapLead: 'Fungura aho duherereye muri Google Maps kugira ngo ubone inzira.',
      mapCta: 'Fungura muri Google Maps',
      mapUrl: 'https://maps.app.goo.gl/GGVeh9pcUptx14oG6',
      mapEmbedUrl: 'https://maps.google.com/maps?q=-1.6948639,29.2523412&z=17&output=embed',
    },
    admissions: {
      label: 'Kwiyandikisha',
      title: 'Injira mu ishuri rifata iterambere ry’umwana wawe nk’ingenzi',
      lead: 'Kwiyandikisha muri La Racine ni ibikorwa byihariye kandi bisobanutse. Dufasha imiryango kubona icyiciro gikwiye no gutangira ishuri n’icyizere.',
      steps: [
        { title: 'Menya ishuri', body: 'Soma ku byerekeye kampasi n’amasomo, hanyuma hitamo kampasi ikwiye umuryango wawe.' },
        { title: 'Saba kuri interineti', body: 'Ohereza ifishi yo kwiyandikisha kuri interineti — nta konti ikenewe. Fata icyemezo cy’amavuko n’ifoto.' },
        { title: 'Igenzura & portal', body: 'Nyuma yo kwemezwa, ishuri rikora konti z’umuryango kugira ngo mukurikire kubahiriza, ibiro, imikoro n’amafaranga.' },
      ],
      ctaApply: 'Saba kuri interineti',
      ctaContact: 'Twandikire ku kwiyandikisha',
      ctaPortal: 'Fungura portal y’umubyeyi',
    },
    contact: {
      label: 'Twandikire',
      title: 'Turiteguye kwakira umuryango wawe',
      lead: 'Twandikire ku biro binyuze kuri telefone cyangwa imeri. Nyuma yo kwiyandikisha, koresha portal yizewe ku buzima bwa buri munsi bw’ishuri.',
      officeTitle: 'Ibiro by’ishuri',
      campusesTitle: 'Telefone za kampasi',
      ctaPortal: 'Portal y’imiryango n’abakozi',
      mapTitle: 'Aho duherereye',
      mapLead: 'Shaka École La Racine kuri Google Maps.',
      mapCta: 'Fungura muri Google Maps',
      mapUrl: 'https://maps.app.goo.gl/GGVeh9pcUptx14oG6',
      mapEmbedUrl: 'https://maps.google.com/maps?q=-1.6948639,29.2523412&z=17&output=embed',
    },
  },
};

export function getPageLabel(slug) {
  return PAGE_LABELS[slug] || slug;
}

export function getDefaultPageData(slug, locale) {
  const enData = defaults.en?.[slug];
  const locData = (defaults[locale] || defaults.en)?.[slug];
  const extra = () => getExtraPageDefault(slug, locale);

  if (!enData && !locData) return structuredClone(extra());
  if (locale === 'en' || !enData) return structuredClone(locData || enData || extra());
  if (!locData) return structuredClone(enData);

  // Incomplete locales (sw/rw) inherit missing home keys from English
  const merge = (base, overlay) => {
    if (!base || typeof base !== 'object' || Array.isArray(base)) return overlay;
    if (!overlay || typeof overlay !== 'object' || Array.isArray(overlay)) return overlay ?? base;
    const out = { ...base, ...overlay };
    for (const key of Object.keys(overlay)) {
      const b = base[key];
      const o = overlay[key];
      if (
        b && o
        && typeof b === 'object' && typeof o === 'object'
        && !Array.isArray(b) && !Array.isArray(o)
      ) {
        out[key] = merge(b, o);
      }
    }
    return out;
  };

  return structuredClone(merge(enData, locData));
}

function getExtraPageDefault(slug, locale) {
  const t = {
    en: {
      announcements: { label: 'Announcements', title: 'Public announcements', lead: 'Important updates from La Racine — view media, documents, and useful links.' },
      news: { label: 'News', title: 'Latest school news', lead: 'Read recent updates from classes and school life.' },
      events: { label: 'Events', title: 'Upcoming events', lead: 'Plan ahead with key school activities and community moments.' },
      gallery: { label: 'Gallery', title: 'School gallery', lead: 'A visual snapshot of learning, activities, and campus life.' },
      newsItem1: 'New term starts next week',
      newsItem2: 'Reading month highlights',
      eventsItem1: 'Parent meeting',
      eventsItem2: 'Sports day',
    },
    fr: {
      announcements: { label: 'Annonces', title: 'Annonces publiques', lead: 'Mises à jour importantes de La Racine — consultez les médias, documents et liens utiles.' },
      news: { label: 'Actualites', title: "Dernieres nouvelles de l'ecole", lead: 'Retrouvez les informations recentes sur les classes et la vie scolaire.' },
      events: { label: 'Evenements', title: 'Evenements a venir', lead: "Preparez-vous avec les activites importantes de l'ecole." },
      gallery: { label: 'Galerie', title: "Galerie de l'ecole", lead: 'Un apercu visuel des apprentissages et de la vie sur campus.' },
      newsItem1: 'La nouvelle periode commence la semaine prochaine',
      newsItem2: 'Moments forts du mois de lecture',
      eventsItem1: 'Reunion des parents',
      eventsItem2: 'Journee sportive',
    },
    sw: {
      announcements: { label: 'Matangazo', title: 'Matangazo ya umma', lead: 'Taarifa muhimu kutoka La Racine — tazama vyombo vya habari, hati na viungo muhimu.' },
      news: { label: 'Habari', title: 'Habari za hivi karibuni za shule', lead: 'Soma taarifa mpya kutoka madarasa na uongozi wa shule.' },
      events: { label: 'Matukio', title: 'Matukio yajayo', lead: 'Panga mapema kwa shughuli muhimu za shule.' },
      gallery: { label: 'Picha', title: 'Picha za shule', lead: 'Muonekano wa maisha ya kujifunza na shughuli za kampasi.' },
      newsItem1: 'Muhula mpya unaanza wiki ijayo',
      newsItem2: 'Mwezi wa usomaji',
      eventsItem1: 'Mkutano wa wazazi',
      eventsItem2: 'Siku ya michezo',
    },
    rw: {
      announcements: { label: 'Amatangazo', title: 'Amatangazo rusange', lead: 'Amakuru y’ingenzi ava muri La Racine — reba amashusho, inyandiko n’inyunganizi zifasha.' },
      news: { label: 'Amakuru', title: "Amakuru mashya y'ishuri", lead: "Soma amakuru aheruka ku masomo no ku buzima bw'ishuri." },
      events: { label: 'Ibikorwa', title: 'Ibikorwa biri imbere', lead: "Tegura mbere ibikorwa by'ingenzi by'ishuri n'umuryango." },
      gallery: { label: 'Amafoto', title: "Amafoto y'ishuri", lead: "Ishusho y'ubuzima bwo kwiga, ibikorwa, na kampasi." },
      newsItem1: 'Igihembwe gishya gitangira icyumweru gitaha',
      newsItem2: 'Ukwezi gusoma',
      eventsItem1: 'Inama yababyeyi',
      eventsItem2: 'Umunsi wa siporo',
    },
  }[locale] || {
    announcements: { label: 'Announcements', title: 'Public announcements', lead: 'Important updates from La Racine — view media, documents, and useful links.' },
    news: { label: 'News', title: 'Latest school news', lead: 'Read recent updates from classes and school life.' },
    events: { label: 'Events', title: 'Upcoming events', lead: 'Plan ahead with key school activities and community moments.' },
    gallery: { label: 'Gallery', title: 'School gallery', lead: 'A visual snapshot of learning, activities, and campus life.' },
    newsItem1: 'New term starts next week',
    newsItem2: 'Reading month highlights',
    eventsItem1: 'Parent meeting',
    eventsItem2: 'Sports day',
  };

  if (slug === 'announcements') {
    return {
      ...t.announcements,
      items: [
        {
          title: 'Announcement 1',
          summary: 'Short summary for the first public announcement.',
          content: 'Full announcement text (optional).',
          images: [],
          documentImageUrl: '',
          documentUrl: '',
          documentLabel: 'Document',
          videoUrl: '',
          linkUrl: '',
          linkLabel: 'Open link',
          publishedAt: '2026-07-10',
          status: 'published',
        },
        {
          title: 'Announcement 2',
          summary: 'Short summary for the second public announcement.',
          content: '',
          images: [],
          documentImageUrl: '',
          documentUrl: '',
          documentLabel: 'Document',
          videoUrl: HERO_VIDEO,
          linkUrl: '',
          linkLabel: 'Open link',
          publishedAt: '2026-07-20',
          status: 'published',
        },
      ],
    };
  }

  if (slug === 'news') {
    return {
      ...t.news,
      items: [
        {
          title: t.newsItem1,
          summary: '',
          content: '',
          imageUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80',
          publishedAt: '2026-07-01',
          category: 'School update',
        },
        {
          title: t.newsItem2,
          summary: '',
          content: '',
          imageUrl: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?auto=format&fit=crop&w=1200&q=80',
          publishedAt: '2026-07-08',
          category: 'Learning',
        },
      ],
    };
  }
  if (slug === 'events') {
    return {
      ...t.events,
      items: [
        {
          title: t.eventsItem1,
          details: '',
          date: '2026-08-10',
          time: '15:00',
          location: 'Main hall',
          type: 'Parent meeting',
        },
        {
          title: t.eventsItem2,
          details: '',
          date: '2026-08-17',
          time: '09:00',
          location: 'School field',
          type: 'Sports',
        },
      ],
    };
  }
  if (slug === 'gallery') {
    return {
      ...t.gallery,
      items: [
        { title: 'Classroom learning', body: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80' },
        { title: 'Primary lesson', body: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?auto=format&fit=crop&w=1200&q=80' },
        { title: 'School activity', body: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&w=1200&q=80' },
      ],
    };
  }
  return undefined;
}

export function getAllDefaultRows() {
  const rows = [];
  for (const locale of WEBSITE_LOCALE_CODES) {
    for (const slug of WEBSITE_PAGE_SLUGS) {
      rows.push({
        slug,
        locale,
        label: getPageLabel(slug),
        data: getDefaultPageData(slug, locale),
      });
    }
  }
  return rows;
}

export { PAGE_LABELS, defaults as WEBSITE_DEFAULTS };
